### PR TITLE
New Excel, Dictionary and Datatable commands

### PR DESCRIPTION
**Pull request by mbhatti125**

### CODE REVIEW

**Comment by saucepleez** [comment]
@mbhatti125 

Thank you for submitting this PR.  I have taken a look and have a few comments:

Excel Get Range - We can probably merge these two into 1 command and add an additional parameter for Output (DataTable, Delimited String) or something similar to that.

Load Dictionary - Can you put together a sample script showing how it is used? I was not sure how to check against the dictionary. Additionally we could break this out into its own group "Dictionary Commands" and have commands like "Create Dictionary", "Load Dictionary (from txt, csv, excel, json)" "Add Dictionary Item" and "Get Dictionary Item".

DataTable Commands - Can you put together sample script showing how it is used?  Additionally, would like to shorten the names to "Add DataRow" and "Remove DataRow" as its causing a scrollbar on render.  Lastly, in the "Create DataTable" and others, we can use a datagridview and a datatable to seperate out each column name as a row instead of requiring delimited strings.

What do you think?

**Comment by mbhatti125** [comment]
@saucepleez 
Sure these all sound like good ideas. I'll start making updates now.

**Comment by saucepleez** [comment]
@mbhatti125 Sure, let me know if you need any help with it.

**Comment by saucepleez** [comment]
@mbhatti125 Thanks for submitting this PR.

**Pull request merged**
