### PR TITLE
UI change etc

### PR DESCRIPTION
**Pull request by rcktrncn**

### CODE REVIEW

**Comment by rcktrncn** [comment]
change tab order
shortcut key in menu
show command icons
Add \r, \n, \t system variables

**Comment by saucepleez** [comment]
Hi, is this ready for review and merge?

**Comment by rcktrncn** [comment]
> 
> 
> Hi, is this ready for review and merge?

Yes, Please.

**Comment by rcktrncn** [comment]
It's really ready review now. please

**Comment by saucepleez** [comment]
@rcktrncn Can you remediate the 2 conflicts? I will approve this, thank you for your help, the changes look good.

**Comment by rcktrncn** [comment]
@saucepleez  Fixed conflicts. Please check.

**Comment by rcktrncn** [comment]
@saucepleez 
I fixed taskt memory leak.Please check it.

**Comment by saucepleez** [comment]
@rcktrncn Thank you for introducing these enhancements!

**Pull request merged**
