### PR TITLE
BeginLoop, ExcelSplitRangeByColumn, RunTask modification, bug fixes

### PR DESCRIPTION
**Pull request by fodfran**
This one is a little random but I made some things I needed for an automation I'm working on. BeginLoop works the same way that BeginIf does. ExcelSplitRangeByColumn groups rows in an excel range by a given column name. I modified RunTask so that you have the option to return variables  from that task. I've also fixed some dictionary commands so that variables could be overwritten. I hope that was okay, let me know if you have any feedback?

### CODE REVIEW

**Comment by fodfran** [comment]
I added two more basic commands. GetFolders and GetFiles. They return lists of directory and file paths respectively from a source folder

**Comment by fodfran** [comment]
I added a BeginMultiLoopCommand that uses code similar to BeginMultiIf and BeginLoop

**Comment by fodfran** [comment]
Added new GetDataRow and GetDataRowValue commands

**Comment by saucepleez** [comment]
Hi, Thank you for putting these changes together.  I assume this branch is fine to be merged now?

**Comment by fodfran** [comment]
Yes, I apologize for all the updates. I'm just about finished with the process I've been working on, so this should be everything. Thank you for developing such an easy to use RPA engine!

**Comment by fodfran** [comment]
I've added a few sample scripts for these commands. Sorry this pull request has gotten so long

**Comment by saucepleez** [comment]
@fodfran Thank you for your hard work on this PR.

**Pull request merged**
