### PR TITLE
Script xml file as intermediage language, advanced search form

### PR DESCRIPTION
**Pull request by rcktrncn**
When script file save, {var} is convert to ⦃var⦄, and some keyword is covert too.
It's enable to smoothly open and run script in different setting taskt.
ex.) if variable marker is < >, ⦃var⦄ is convert to \<var\> automatically, when open file.

Add new search form.It enable to search in parameter values, comment, and command name.

### CODE REVIEW

**Comment by rcktrncn** [comment]
add Replace form

**Comment by rcktrncn** [comment]
add sample script form

**Comment by rcktrncn** [comment]
add command filter

**Comment by rcktrncn** [comment]
Add List Commands group

**Comment by rcktrncn** [comment]
Added commands to manipulate data types of List, Dictionary and DataTable.
Added commands to use these data types in Excel and Web browser commands.

**Comment by rcktrncn** [comment]
Support auto update.

**Comment by saucepleez** [comment]
Wow, you did a lot of work here, it looks really good, thank you

**Pull request merged**
